### ISSUE TITLE
Files are created with wrong file permissions

### ISSUE THREAD

**Issue by sascha-egerer** [mia3/crossmedia_fourallportal#12]
The extension stores file in the FAL Local Driver but it does not use the API to do that. So files are created with wrong file permissions which makes the extension unusable.
The extension must use the API when dealing with assets.
e.g. in `ApiClient::saveDerivate()`

**Comment by NamelessCoder** [comment]
This issue is kept open because it is true that the usage can be improved, but this is not the cause of the actual problem. To clarify:

* The extension uses Curl to retrieve the file to a temporary location
* It then moves this file away from the temporary location
* Finally, the FAL API is used to create a file and set its contents

The last step is the vital one and is confirmed working regardless of permissions used in the first and second steps. As long as the temporary folder and fileadmin are writable by the user, the thing to take away from this is that *the TYPO3 API is used in the critical location and permissions should not be to blame for failing to save a derivate*. One of the first steps can be avoided (hence this issue stays open). If memory usage is not a hindrance we can also stream memory contents directly into FAL without saving any temporary files.

We're still locating the actual cause but suspect problems in the PSD conversion routine. Incorrect permissions are a side effect, not the root cause.
